name: digitalchumps
favicon: null
layout_spectrum: 0.60194
typography_spectrum: 0.41582
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8bc5f4'
    - '#005eab'
    - '#000000'
    - '#638dae'
    - '#ffffff'
  brandStrength: 0.8125
  lightness: 0.0625
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
